### ISSUE TITLE
Bug: Images without alt text are ignored

### ISSUE THREAD

**Issue by ad-si** [kamalsacranie/anki-panky#3]
Currently images without an alt text are ignored.

So this works:
```md
![x](images/test.png)
```

but this doesn't:
```md
![](images/test.png)
```

**Comment by kamalsacranie** [comment]
Hi Adrian,

Thanks for taking the risk to be an early adopter haha. I'll fix this in the coming week. Also could I ask if you're on a linux machine? Just wanted to know to confirm that my compiled release for linux works.

**Comment by ad-si** [comment]
Haha, no problem! 😄
Thanks for building it! It's exactly what I was looking for 🙇‍♂️

No, sorry, I'm using the macOS build from the releases.

**Comment by kamalsacranie** [comment]
Fixed by #6
