### ISSUE TITLE
Feature: Add syntax highlighting

### ISSUE THREAD

**Issue by ad-si** [kamalsacranie/anki-panky#5]
It would be really cool if the code was syntax highlighted!

That's actually the main reason why I'm looking for an alternative to the embedded Anki editor. 😅

**Comment by kamalsacranie** [comment]
Hi Adrian. This is definitely on my todo list and it's really annoying that it ended up working not out the box. It's definitely doable as Pandoc does native syntax highlighting. I just need to investigate on how to incorporate it.

**Comment by kamalsacranie** [comment]
The new release has syntax highlighting

**Comment by ad-si** [comment]
This is really cool! Thanks for your efforts! 😁

Just tried it out with a big deck I'm working on (> 550 cards for learning Rust - I'll open source it next week) and looks really nice 🙌

**Comment by ad-si** [comment]
BTW: You should announce Anki Panky on https://discourse.haskell.org! It's a fantastic tool and others might enjoy it too! ☺️

**Comment by kamalsacranie** [comment]
Thanks so much for the kind words, I'm so glad you like it. Great idea, I'll get around to letting people know about it soon! Hopefully then we can get it well-known enough to get it on homebrew 💪

**Comment by ad-si** [comment]
FYI @kamalsacranie: It's online -> https://github.com/ad-si/Rust-Flashcards
